apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rcds-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: rcds-operator
  namespace: default
roleRef:
  kind: Role
  name: rcds-operator
  apiGroup: rbac.authorization.k8s.io
